In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
dataset = pd.read_excel(r'DataFinal17-20.xlsx',sheet_name='2020')

In [3]:
dataset = dataset.drop(['Total'], axis=1)

In [4]:
print(dataset)

    SrNo     District  Homicide/Murder  Causing death by negligence  Hurt  \
0      1   Ahmednagar              254                          620  1826   
1      2        Akola              114                          116  1345   
2      3     Amravati              201                          354  2133   
3      4    Aurangbad              139                          386  1869   
4      5         Beed              206                          308  1233   
5      6     Bhandara               41                          141   486   
6      7     Buldhana              122                          293  2099   
7      8   Chandrapur              105                          234  1147   
8      9        Dhule               84                          352   433   
9     10   Gadchiroli               65                          135   303   
10    11       Gondia               50                          131   311   
11    12      Hingoli               75                          119   649   

In [5]:
X = dataset.iloc[:, 2:14].values
y = dataset.iloc[:, 19:20].values
y2 = dataset.iloc[:, 20:21].values

In [6]:
print(X)

[[  254   620  1826   543   369     0    92   905  3104   220 30535   221]
 [  114   116  1345   245    76     0    28   111   946    86  4244   213]
 [  201   354  2133   461   190     0    97   144  2198   250  3921   164]
 [  139   386  1869   335   242     0    80   428  3821   265  4292   411]
 [  206   308  1233   248    91     0    50   508  1002   104  1858   111]
 [   41   141   486    88    71     0    16    43   676    60  1051    54]
 [  122   293  2099   313   110     0    36   320  1269   102  3024   104]
 [  105   234  1147   194   152     1    46    84   980   108  2235   355]
 [   84   352   433    80    98     1    14   205   781    77  1237   175]
 [   65   135   303    55    32     0    17    21   302    41   427    27]
 [   50   131   311    57    40     0    18    23   400    30   996   134]
 [   75   119   649    73    27     0    15   140   436    35  1314    30]
 [  192   439   901   259   187     0    34   440  2045   248  4353   256]
 [  133   209  1436   208

In [7]:
print(y)

[[19.0948287]
 [20.7002159]
 [20.9319821]
 [19.8761653]
 [18.990088 ]
 [21.177658 ]
 [20.5292147]
 [19.9615398]
 [20.9042201]
 [20.184871 ]
 [21.4549477]
 [19.7173703]
 [21.0076578]
 [19.8346659]
 [16.7049873]
 [18.4087934]
 [19.0759837]
 [19.1538231]
 [21.1458004]
 [19.1382514]
 [21.7468548]
 [19.9974533]
 [18.185332 ]
 [19.2608384]
 [18.5204303]
 [18.2376278]
 [16.990215 ]
 [16.8523973]
 [17.6804639]
 [16.3492193]
 [17.6599188]
 [19.2183307]
 [20.745319 ]
 [20.1119123]
 [20.3899385]]


In [8]:
print(y2)

[[74.7479789]
 [77.0081678]
 [77.7523039]
 [75.3433139]
 [75.7531324]
 [79.6570127]
 [76.1841701]
 [79.2961468]
 [74.7748979]
 [79.9947956]
 [80.1960712]
 [77.1493722]
 [75.5626039]
 [75.8816345]
 [74.2432527]
 [76.5603828]
 [72.8776559]
 [72.8751786]
 [79.0881546]
 [77.3209555]
 [74.123996 ]
 [73.7898023]
 [76.0419642]
 [76.774776 ]
 [73.8567437]
 [73.4445392]
 [73.3120233]
 [74.5814773]
 [74.018261 ]
 [73.5594128]
 [75.9063906]
 [72.9780897]
 [78.6021946]
 [77.1312586]
 [78.1306846]]


In [9]:
print(dataset)

    SrNo     District  Homicide/Murder  Causing death by negligence  Hurt  \
0      1   Ahmednagar              254                          620  1826   
1      2        Akola              114                          116  1345   
2      3     Amravati              201                          354  2133   
3      4    Aurangbad              139                          386  1869   
4      5         Beed              206                          308  1233   
5      6     Bhandara               41                          141   486   
6      7     Buldhana              122                          293  2099   
7      8   Chandrapur              105                          234  1147   
8      9        Dhule               84                          352   433   
9     10   Gadchiroli               65                          135   303   
10    11       Gondia               50                          131   311   
11    12      Hingoli               75                          119   649   

In [10]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)
X_train, X_test, y2_train, y2_test = train_test_split(X, y2, test_size = 0.2, random_state = 0)

In [11]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
sc_y = StandardScaler()
sc_y2 = StandardScaler()
X = sc_X.fit_transform(X)
y = sc_y.fit_transform(y)
y2 = sc_y2.fit_transform(y2)

In [12]:
# Fitting SVR to the dataset
from sklearn.svm import SVR
regressor = SVR(kernel = 'rbf')
#rbf = Gaussian Radial Basis Function Kernel
yfit = regressor.fit(X, y)
y2fit =regressor.fit(X, y2)

c:\users\welcome\appdata\local\programs\python\python39\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)
c:\users\welcome\appdata\local\programs\python\python39\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


In [13]:
# Predicting a new result

y_pred = regressor.predict(sc_X.transform(np.array([[254,620,1826,543,369,0,92,905,3104,220,30535,221]])))
y_pred2 = regressor.predict(sc_X.transform(np.array([[254,620,1826,543,369,0,92,905,3104,220,30535,221]])))


y2_pred = regressor.predict(sc_X.transform(np.array([[84,352,433,80,98,1,14,205,781,77,1237,175]])))
y2_pred2 = regressor.predict(sc_X.transform(np.array([[84,352,433,80,98,1,14,205,781,77,1237,175]])))


y3_pred = regressor.predict(sc_X.transform(np.array([[62,133,255,44,57,0,17,116,429,38,2930,3053]])))
y3_pred2 = regressor.predict(sc_X.transform(np.array([[62,133,255,44,57,0,17,116,429,38,2930,3053]])))

In [14]:
y_pred = sc_y.inverse_transform(np.array(y_pred).reshape(1,-1))
y_pred2 = sc_y2.inverse_transform(np.array(y_pred2).reshape(1,-1))

y2_pred = sc_y.inverse_transform(np.array(y2_pred).reshape(1,-1))
y2_pred2 = sc_y2.inverse_transform(np.array(y2_pred2).reshape(1,-1))

y3_pred = sc_y.inverse_transform(np.array(y3_pred).reshape(1,-1))
y3_pred2 = sc_y2.inverse_transform(np.array(y3_pred2).reshape(1,-1))

In [17]:
def district_pred(a,b):
    target_district = ""
    min = 999
    num = 0
    for i in range(len(dataset['Latitude'])):
            if (abs(a-dataset['Latitude'][i])+abs(b-dataset['Longitude'][i]))<min:
                min = abs(a-dataset['Latitude'][i])+abs(b-dataset['Longitude'][i])
                target_district = dataset['District'][i]
                num = i
    return target_district,num

In [18]:
y_preds = [y_pred,y2_pred,y3_pred]
y_pred2s = [y_pred2,y2_pred2,y3_pred2]

for i in range(len(y_preds)):
    str, x = district_pred(y_preds[i],y_pred2s[i])
    print(str)
    print(dataset['Latitude'][x])
    print(dataset['Longitude'][x])

Pune
18.5204303
73.8567437
Jalna
19.8346659
75.8816345
Washim
20.1119123
77.1312586
